### ISSUE TITLE
MagicHome support

### ISSUE THREAD

**Issue by DJONvl** [soef/ioBroker.wifilight#1]
https://ru.aliexpress.com/item/LED-Strip-5050-RGB-Set-5-meter-RGB-LED-Strip-Mini-Wifi-RGB-LED-Controller/32714233657.html
добавь пожалуйста поддержку этих устройств:
exports.knownDeviceNames = {
    'HF-LPB100-ZJ200': { type: 'LD382A' /*, port: 5577*/ },
    'HF-A11-ZJ002':    { type: 'LW12' },
	'AK001-ZJ100':	   { type: 'LD382A' /*, magichome port: 5577*/ }
};

**Comment by soef** [comment]
Done, thank you.
