### ISSUE TITLE
wifilight looses connection to device

### ISSUE THREAD

**Issue by Bogoli17** [soef/ioBroker.wifilight#13]
I am controlling a "Magic UFO RGB Controller" with wifilight and it normally works great.
But the wifilight adapter looses the connection to iobroker after about 5 minutes.
After loosing the connection it is not reacting on any command anymore.
The Magic Home app works normal even if the connection to wifilight is broken so the wifi controller works as it should.
Here is the important part of the Log from startup till crash (the crash is marked bold):

**wifilight.0	2017-11-12 09:05:03.100	debug	[192.168.11.140] onClose hasError=false client=[object Object]**
wifilight.0	2017-11-12 09:00:03.120	debug	[192.168.11.140] onData: {'on':false,'progNo':97,'progOn':true,'preogSpeed':10,'red':143,'green':0,'blue':204,'white':255}
wifilight.0	2017-11-12 09:00:03.118	debug	[192.168.11.140] onData: raw: 81 04 24 61 21 0a 8f 00 cc ff 03 00 00 92
wifilight.0	2017-11-12 09:00:03.117	debug	raw data: 81 04 24 61 21 0a 8f 00 cc ff 03 00 00 92
wifilight.0	2017-11-12 09:00:03.116	debug	raw data length: 14
wifilight.0	2017-11-12 09:00:03.045	debug	self.client.connect: connected
wifilight.0	2017-11-12 09:00:03.044	debug	[192.168.11.140] write: 81 8a 8b 96
wifilight.0	2017-11-12 09:00:03.036	debug	[192.168.11.140] 192.168.11.140 connected
wifilight.0	2017-11-12 09:00:02.852	debug	Schedule restart: */59 * * * *
wifilight.0	2017-11-12 09:00:02.677	info	starting. Version 0.1.9 in /opt/iobroker/node_modules/iobroker.wifilight, node: v4.8.6
wifilight.0	2017-11-12 09:00:02.625	debug	statesDB connected
wifilight.0	2017-11-12 09:00:02.520	debug	objectDB connected
host.odroid-server	2017-11-12 09:00:01.083	info	instance system.adapter.wifilight.0 started with pid 3130
host.odroid-server	2017-11-12 09:00:00.067	info	Restart adapter system.adapter.wifilight.0 because enabled

As you can see it crashes even if i do not send any command (it crashes too if i send commands..)
The connection lasts only 5 minutes then it´s gone.

Here some additional informations:
wifi LED adapter: HF-LPB100-ZJ200	LD382A	Port: 5577
iobroker version: 2.0.9
wifilight Version: 0.1.9

**Comment by soef** [comment]
Hi, the highlighted line is just a debug output. onClose means that the socket was closed. Are you sure the adapter crashes? If, please send me the stacktrace.

If you use the adapter, no other software modules should access the wifilightModule. I mean the wifilight module can only handle one connection.

**Comment by Bogoli17** [comment]
Yes i'm shure the connection is lost ... and the status of the device changes (reachable) to false.
I had no other connection ..... 
Now i stopped using the rgb controller due to a other reason, i cant deliver more detailed information ...
So if i am the only person with this problem you may close this issue.

Thank you for your fast reply

**Comment by Bogoli17** [comment]
Yes i'm shure the connection is lost ... and the status of the device changes (reachable) to false.
I had no other connection ..... 
Now i stopped using the rgb controller due to a other reason, i cant deliver more detailed information ...
So if i am the only person with this problem you may close this issue.

Thank you for your fast reply
