### ISSUE TITLE
Gerät nicht unterstützte AK001—ZJ200

### ISSUE THREAD

**Issue by matze1708** [soef/ioBroker.wifilight#16]
Hallo lässt sich das ampassen?

wifilight.0	2017-12-20 17:30:04.218	error	wrong device type. not yet supported!
wifilight.0	2017-12-20 17:30:04.216	error	Known names are: HF-LPB100-ZJ200, HF-LPB100-ZJ002, HF-A11-ZJ002, Mi-Light, AK001-ZJ100
wifilight.0	2017-12-20 17:30:04.216	error	config.device AK001-ZJ200 is not a known device. Skipping this device!

**Comment by soef** [comment]
I have merged your pull request.

**Comment by matze1708** [comment]
Danke, ich hatte wie ich diesen Code bei mir händisch einfügte, trotzdem noch die Meldung bekommen,
Wrong Device Type, not yet supported.

Habe ich da was vergessen?

**Comment by matze1708** [comment]
Auch nach Update, gleiche Meldung wie oben

**Comment by soef** [comment]
Hattest Du den Adapter nach der Code-Änderung neu gestartet? Ansonsten müssten die Änderungen ausreichen.

**Comment by matze1708** [comment]
Ja mehrfach schon, kommt direkt diese Meldung.

Hatte schon andere Treiber probiert, bleibt beim gleichen

**Comment by soef** [comment]
Hier weiter [...](https://github.com/soef/ioBroker.wifilight/issues/14#issuecomment-354011340)
