### ISSUE TITLE
LED Adapter LD382

### ISSUE THREAD

**Issue by simpixo** [soef/ioBroker.wifilight#2]
Hello

i have the LED Controller XCSOURCE Magic UFO-WiFi LED-Controller LD382 but your Adapter don't work with them i get the following message

wifilight.0	2016-12-21 21:35:10.367	error	wrong device type. not yet supported!

whats wrong? Could i help you to modify the adapter that it works with my controller?

Thanks

**Comment by soef** [comment]
Hello,

it seems as if the device type is empty. Have a look to the configuration. The column "Type" ofr your device must contain LD382

if it dosn't work, let me now.

**Comment by vladitep** [comment]
same problem, my device shown as HF-LPB100-ZJ002, but config for HF-LPB100-ZJ200 or another device what exist in devices.js file doesnt work, codes in [this article](https://github.com/sidoh/ledenet_api) doesnt work too. I found this link - http://www.emessaging.biz/blog/?p=629 (my nod32 doesn't allow me to connect to this site, but through google translate all ok :)) and codes from this link works for my UFO wifi led controller.
I edited devices.js file for simple on/off () and status request:
useCheckSum: true
on: [0x71, 0x23],
off: [0x71, 0x24],
statusRequest [0x81, 0x8A, 0x8B],
but i dont have skills for write a complete support for this type of device.

**Comment by simpixo** [comment]
I have the same controller as vladitep. I can't find any type entry in the configuration. Only the one and almost equal entry **HF-LPB100-ZJ002** but can't change it to `LD382`.

But i bought my controller at amazon and they describe it as LD382

**Comment by vladitep** [comment]
Maybe it is LD382, but wifilight support only LD382**A**
You can modify file devices.js (opt/iobroker/node_modules/iobroker.wifilight) find section export.knownDeviceNames
and add line
'HF-LPB100-ZJ002': {type: 'LD382A' },
Now when wifilight sees HF-LPB100-ZJ002 it will use codes from LD382A.
But for me it doesnt work.
by the way, although official MiLight app works with my controller, but when i associated it with MiLight codes in devices.js it doesnt work

**Comment by simpixo** [comment]
Thanks VLADITEP for the solution. It works for me! You are my Hero ;)

soef could you please add my controller to your Adapter?

Thanks

**Comment by soef** [comment]
@simpixo: i will add the device. Is it a LD382A or LD382?
@vladitep: if the above sequences for on/off and statusRequest are working, i will add a new device called e.g. UFO.

btw: you don't have to use the add device button. You can manually add a device by pressing the small + button below. And then you can select the wanted type.

**Comment by simpixo** [comment]
The controller description say it is a LD382! But at the moment it works as LD382A 😉

I must change it or your Adapter update change it 😜😂

Thanks

**Comment by vladitep** [comment]
@soef: yes, for  HF-LPB100-ZJ002 codes for on, off and request is works, with checksum enabled. I can scan milight app for other codes that app sends to controller, like programs, color changing and so, but my skills don't allow me to add it to wifiligh adapter

**Comment by simpixo** [comment]
I have to correct me. My controller works as LD382A but not all function works, i can't power on and off the LED Stripe and the programs don't work :(

**Comment by soef** [comment]
I have added HF-LPB100-ZJ002 as LD382 device with the same configuration as LD382A. I think the only different is that LD382 has no white channel?? This is only for auto discover.

I've added a UFO device with the sequences from the website above. The response length is set to 17, but i do  not know if it is korrekt. There is a debg output if you switch the logLevel of the adapter to debug.

**Comment by soef** [comment]
@vladitep: I think you have to go to the configuration and set the type manually to UFO.

**Comment by simpixo** [comment]
Thats not correct my controller have an output for a white channel :-) But it works now correctly with your Adapter. Did you change something else in your code? 

Very cool, thanks!!!

**Comment by simpixo** [comment]
But now i get the following error when i change something manually in the objects. Whats wrong?

TypeError:	2016-12-23 08:40:27.713	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
TypeError:	2016-12-23 08:40:27.713	error	at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
TypeError:	2016-12-23 08:40:27.713	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:228:12)
TypeError:	2016-12-23 08:40:27.713	error	at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:270:10)
TypeError:	2016-12-23 08:40:27.713	error	at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
TypeError:	2016-12-23 08:40:27.713	error	at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:45:30)
TypeError:	2016-12-23 08:40:27.713	error	at Object.that.states.States.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2226:37)
TypeError:	2016-12-23 08:40:27.713	error	at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1057:21)
TypeError:	2016-12-23 08:40:27.713	error	at Object.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:139:12)
TypeError:	2016-12-23 08:40:27.713	error	at WifiLight.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:211:22)
TypeError:	2016-12-23 08:40:27.713	error	this.dev.updateVal is not a function

**Comment by vladitep** [comment]
@simpixo: only on, off and status request added for our type of controller. Other objects not exist.
My controller have white channel too.

**Comment by soef** [comment]
@simpixo: there was an old function called, when setting the transition time state. this is fixed now. 
-
ok, added the rgbw command for Setting the white Level.

**Comment by DJONvl** [comment]
обновил до 0.0.36 с MagicHome перестал работать
`host.localhost	2016-12-27 22:37:39.655	error	instance system.adapter.wifilight.0 terminated with code 0 (OK)
wifilight.0	2016-12-27 22:37:39.632	info	terminating
wifilight.0	2016-12-27 22:37:39.589	error	at process._tickCallback (node.js:375:17)
wifilight.0	2016-12-27 22:37:39.589	error	at nextTickCallbackWith3Args (node.js:469:9)
wifilight.0	2016-12-27 22:37:39.589	error	at dgram.js:214:18
wifilight.0	2016-12-27 22:37:39.589	error	at exports._exceptionWithHostPort (util.js:930:20)
wifilight.0	2016-12-27 22:37:39.589	error	at Object.exports._errnoException (util.js:907:11)
wifilight.0	2016-12-27 22:37:39.589	error	Error: bind EADDRINUSE 0.0.0.0:48899
wifilight.0	2016-12-27 22:37:39.576	error	uncaught exception: bind EADDRINUSE 0.0.0.0:48899`

**Comment by soef** [comment]
Hello,

as the error message shows: EADDRINUSE 0.0.0.0:48899, on this machine port 48899 is already in use.
