### ISSUE TITLE
HTTP Request des Adapter

### ISSUE THREAD

**Issue by ihavenonick** [soef/iobroker.wifilight#22]
Hallo,
hat eigentlich nichts direkt mit dem Adapter zu tun, da Du aber hier definitiv der Mann mit mehr Wissen bist, erhoffe ich mir doch Hilfe.
Ich möchte einfach ein Controller der mit dem Adapter über IOBroker läuft, auch schnell und einfach über HTTP Request mit dem Handy aus und ein schalten. Dazu fehlt mir allerdings der besagte HTTP Request. Eigentlich läuft das im Adapter wohl genau so ab, oder Du weißt zumindest mal wie der Befehl hier aufgebaut sein müsste. Kannst Du mir hier weiterhelfen?

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.wifilight-community#7
