### ISSUE TITLE
connection to the light module

### ISSUE THREAD

**Issue by rickfl92** [soef/ioBroker.wifilight#8]
Since the host update, the WIFILIGHT adapter loses the connection to the light module after 1 minute.
After restarting the adapter it will work again for 1 minute

**Comment by soef** [comment]
Can you activate the debug loging on the Instances tap and check the entries of the wifilight Adapter on the log-tap?

**Comment by rickfl92** [comment]
http://forum.iobroker.net/viewtopic.php?f=20&t=6711&hilit=wifilight

I will look at the log when I am at home

**Comment by soef** [comment]
Hi, I think i fond the problem and it is fixed in version 0.1.6
